name = "extrive-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "extrive-api"

[env.production.vars]
SMTP2GO_API_KEY = "api-519E873AF2A14B58826E02D815A35BFA"
EMAIL_USER = "info@extriveinnovations.com"
TO_EMAIL = "info@extriveinnovations.com"
CC_EMAIL = "extriveinnovations.com@gmail.com"
NODE_ENV = "production"
FRONTEND_URL = "https://extrivefrontend.pages.dev"
